# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-08 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodtaskerapp', '0003_auto_20170808_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carta',
            old_name='entrantes',
            new_name='plato',
        ),
        migrations.RenameField(
            model_name='carta',
            old_name='nombre',
            new_name='restaurante',
        ),
    ]
