# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-16 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtaskerapp', '0003_auto_20170816_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='dishes/'),
        ),
        migrations.AlterField(
            model_name='plato',
            name='precio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
