# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-20 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtaskerapp', '0004_auto_20170816_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='phone',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
